version: "3.9"  
services:
  ansible:
    build: 
      context: ./ansible_base
      dockerfile: Dockerfile
    container_name: ansible_controller
    volumes:
      - type: bind
        source: ./ansible_files
        target: /home/ansible_controller/ansible_files
  target:
    build: 
      context: ./hello-world
      dockerfile: Dockerfile
    container_name: hello_world
    ports:
      - "3000:3000"
      - "22:22"