name: My cool Workflow

on:
  push: 
  pull_request:
  workflow_dispatch:

jobs:
    myFirstJob:
              name: First job
              runs-on: ubuntu-latest
              steps:
              - name: Step One
                uses: actions/checkout@v3
              - name: Step Two
                run: |
                  touch newFile.yaml
                  echo "Please Alexis is Friday let me escape" >> newFile.yaml
                  cat newFile.yaml
                  pwd
